version: '3.3'
services:

  zookeeper:
    image: zookeeper:3.4.11
    restart: always
    ports:
      - "2181:2181"
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.18.0.2:2888:3888 server.2=172.18.0.3:2888:3888 server.3=172.18.0.4:2888:3888
    networks:
      zoo-net:
        ipv4_address: 172.18.0.2

  zookeeper1:
    image: zookeeper:3.4.11
    restart: always
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"
    container_name: zookeeper1
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=172.18.0.2:2888:3888 server.2=172.18.0.3:2888:3888 server.3=172.18.0.4:2888:3888
    networks:
      zoo-net:
        ipv4_address: 172.18.0.3

  zookeeper2:
    image: zookeeper:3.4.11
    restart: always
    ports:
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"
    container_name: zookeeper2
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=172.18.0.2:2888:3888 server.2=172.18.0.3:2888:3888 server.3=172.18.0.4:2888:3888
    networks:
      zoo-net:
        ipv4_address: 172.18.0.4

networks:
  zoo-net:
    external:
      name: zoo-net
